CREATE WAREHOUSE IF NOT EXISTS WH_LENDING
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS LENDING_CLUB;

CREATE SCHEMA IF NOT EXISTS LENDING_CLUB.RAW;        -- Bronze
CREATE SCHEMA IF NOT EXISTS LENDING_CLUB.SILVER;    -- Silver (dbt)
CREATE SCHEMA IF NOT EXISTS LENDING_CLUB.GOLD;  -- Gold (dbt)

USE DATABASE LENDING_CLUB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FMT
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NA');

CREATE OR REPLACE STAGE BLOB_STAGE
  URL = 'azure://creditriskstrg0.blob.core.windows.net/lendingclub-raw'
  CREDENTIALS = (AZURE_SAS_TOKEN = 'sv=2026-02-06&ss=bt&srt=co&sp=rltfx&se=2026-09-06T00:48:41Z&st=2026-08-05T16:33:41Z&spr=https&sig=3jf7WKZirT6X%2BP0tBuiMQxovEm5%2BDaSRUtb5naTa1VQ%3D')
  FILE_FORMAT = CSV_FMT;

LIST @BLOB_STAGE;
LIST @BLOB_STAGE/landing;
USE DATABASE LENDING_CLUB;
USE SCHEMA RAW;

EXECUTE DBT PROJECT LENDING_CLUB.ANALYTICS.lendingclub_dbt_project
  ARGS = 'build';


